version: '3.8'

services:
    frontend:
        image: frontend:1.0.0
        container_name: frontend
        build:
            context: ./src/frontend
        ports:
            - 80:80
        depends_on:
            - game-service
            - gameprovider-service
            - chat-service
        volumes:
            - ./src/frontend/nginx.prod.conf:/etc/nginx/nginx.conf
            - ./src/frontend/cloudflare-ips.conf:/var/www-allow/cloudflare-ips.conf

    game-service:
        image: game-service:1.0.0
        build:
            context: ./src/game-service/Game.Application
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051

    gameprovider-service:
        image: gameprovider-service:1.0.0
        build:
            context: ./src/gameprovider-service
        expose:
            - 50052
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50052
            GAME_SERVICES: "{\"name\":\"Europe\",\"protocol\":\"ws\",\"url\":\"maplefighters.io/europe/\"}"

    chat-service:
        image: chat-service:1.0.0
        build:
            context: ./src/chat-service
        expose:
            - 50054
        environment:
            PORT: 50054
