version: '3.8'

services:
    frontend:
        image: nginx:1.20.1-alpine
        container_name: frontend
        build:
            context: ./src/frontend
        ports:
            - 80:80
        depends_on:
            - auth-service
            - character-service
            - game-service
            - gameprovider-service
            - chat-service
        volumes:
            - ./src/frontend/nginx.conf:/etc/nginx/nginx.conf

    auth-service:
        image: auth-service:1.0.0
        build:
            context: ./src/auth-service
        expose:
            - 50050
        depends_on:
            - mongo
        external_links:
            - mongo
        environment:
            ASPNETCORE_ENVIRONMENT: Production
            ASPNETCORE_URLS: http://0.0.0.0:50050
            DATABASE_URL: mongodb://mongo:27017/maple_fighters

    character-service:
        image: character-service:1.0.0
        build:
            context: ./src/character-service
        expose:
            - 50053
        depends_on:
            - postgres
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50053
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    game-service:
        image: game-service:1.0.0
        build:
            context: ./src/game-service/Game.Application
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051

    gameprovider-service:
        image: gameprovider-service:1.0.0
        build:
            context: ./src/gameprovider-service
        expose:
            - 50052
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50052

    chat-service:
        image: chat-service:1.0.0
        build:
            context: ./src/chat-service
        expose:
            - 50054
        environment:
            PORT: 50054

    postgres:
        image: postgres:13
        container_name: character-db
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    mongo:
        image: mongo:5.0.2
        container_name: user-db
        expose:
            - 27017
