version: '3.8'

services:
    frontend:
        image: frontend:1.0.0
        container_name: frontend
        build:
            context: ./src/frontend
        ports:
            - 80:80
        depends_on:
            - game-service
        volumes:
            - ./src/frontend/nginx.prod.conf:/etc/nginx/nginx.conf

    game-service:
        image: game-service:1.0.0
        build:
            context: ./src/game-service/Game.Application
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051
