version: '3.8'

services:
    frontend:
        image: frontend
        build:
            context: ./src/frontend
            dockerfile: Dockerfile.dev
            args:
                ENVIRONMENT: Development
        ports:
            - 80:80
        depends_on:
            - auth-service
            - character-service
            - game-service
            - gameprovider-service
            - chat-service

    auth-service:
        image: auth-service
        build:
            context: ./src/auth-service
        expose:
            - 50050
        depends_on:
            - mongo
        external_links:
            - mongo
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_URLS: http://0.0.0.0:50050
            DATABASE_URL: mongodb://mongo:27017/maple_fighters

    character-service:
        image: character-service
        build:
            context: ./src/character-service
        expose:
            - 50053
        depends_on:
            - postgres
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50053
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    game-service:
        image: game-service
        build:
            context: ./src/game-service/Game.Application
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051
            FLECK_LOG: Info
            IM_LOG: Debug
            GAME_LOG: Debug

    gameprovider-service:
        image: gameprovider-service
        build:
            context: ./src/gameprovider-service
        expose:
            - 50052
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50052
            GAME_SERVICES: "[{\"name\":\"Local Game\",\"protocol\":\"ws\",\"url\":\"localhost/game/\"}]"

    chat-service:
        image: chat-service
        build:
            context: ./src/chat-service
        expose:
            - 50054
        environment:
            PORT: 50054

    postgres:
        image: postgres:13
        container_name: character-db
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    mongo:
        image: mongo:5.0.2
        container_name: user-db
        expose:
            - 27017
