version: '3.8'

services:
    frontend:
        image: maplefighters/frontend
        ports:
            - 80:80
        depends_on:
            - auth-service
            - character-service
            - game-service
            - gameprovider-service
            - chat-service

    auth-service:
        image: maplefighters/auth-service
        expose:
            - 50050
        depends_on:
            - auth-db
        environment:
            ASPNETCORE_ENVIRONMENT: Production
            ASPNETCORE_URLS: http://0.0.0.0:50050
            DATABASE_URL: mongodb://auth-db:27017/${AUTH_DB_NAME}

    character-service:
        image: maplefighters/character-service
        expose:
            - 50053
        depends_on:
            - character-db
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50053
            DATABASE_URL: postgres://${CHARACTER_DB_USER}:${CHARACTER_DB_PASSWORD}@character-db:5432/${CHARACTER_DB_NAME}

    game-service:
        image: maplefighters/game-service
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051
            FLECK_LOG: Info
            IM_LOG: Debug
            GAME_LOG: Debug
            CONFIG_ENV: main

    gameprovider-service:
        image: maplefighters/gameprovider-service
        expose:
            - 50052
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50052
            GAME_SERVICES: "[{\"name\":\"Europe\",\"protocol\":\"ws\",\"url\":\"maplefighters.io/europe/\"}]"

    chat-service:
        image: maplefighters/chat-service
        expose:
            - 50054
        environment:
            PORT: 50054

    auth-db:
        image: mongo:5.0.2
        restart: "always"
        expose:
            - 27017
        volumes:
            - mongo:/mongodb/data

    character-db:
        image: postgres:13
        restart: "always"
        expose:
            - 5432
        environment:
            POSTGRES_USER: ${CHARACTER_DB_USER}
            POSTGRES_PASSWORD: ${CHARACTER_DB_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
  mongo: ~
