version: '3.8'

services:
    frontend:
        image: maplefighters/frontend:2.0.0
        ports:
            - 80:80
        depends_on:
            - game-service
    game-service:
        image: maplefighters/game-service:2.0.0
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051
            FLECK_LOG: Info
            IM_LOG: Debug
            GAME_LOG: Debug
            CONFIG_SOURCE: v2.0
            MAX_CONNECTIONS: 100
