apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authservice
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:50050
            - name: DATABASE_URL
              value: mongodb://auth-db:27017/users
          image: authservice
          name: authservice
          ports:
            - containerPort: 50050
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authservice
  name: authservice
spec:
  type: ClusterIP
  ports:
    - name: authservice-port
      port: 50050
      targetPort: 50050
  selector:
    app: authservice
