apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: maplefighters/auth-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50050
          livenessProbe:
            httpGet:
              path: /healthz
              port: 50050
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 50050
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:50050
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: maple-fighters
spec:
  type: ClusterIP
  ports:
    - name: auth-service-port
      port: 50050
      targetPort: 50050
  selector:
    app: auth-service
