apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: maplefighters/auth-service:latest
          ports:
            - containerPort: 50050
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:50050
            - name: DATABASE_URL
              value: mongodb://mongo-auth:27017/users
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - name: auth-service-port
      port: 50050
      targetPort: 50050
  selector:
    app: auth-service
