apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-service
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-service
  template:
    metadata:
      labels:
        app: character-service
    spec:
      containers:
        - name: character-service
          image: maplefighters/character-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50053
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres-character:5432/postgres
            - name: IP_ADDRESS
              value: 0.0.0.0:50053
            - name: RUST_BACKTRACE
              value: full
            - name: RUST_LOG
              value: info
          resources:
            requests:
              cpu: 100m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: character-service
  namespace: maple-fighters
spec:
  type: ClusterIP
  ports:
    - name: character-service-port
      port: 50053
      targetPort: 50053
  selector:
    app: character-service
