apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chatservice
  name: chatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatservice
  template:
    metadata:
      labels:
        app: chatservice
    spec:
      containers:
        - env:
            - name: PORT
              value: "50054"
          image: chatservice
          name: chatservice
          ports:
            - containerPort: 50054
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatservice
  name: chatservice
spec:
  type: ClusterIP
  ports:
    - name: chatservice-port
      port: 50054
      targetPort: 50054
  selector:
    app: chatservice
