apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: maplefighters/chat-service:latest
          ports:
            - containerPort: 50054
          env:
            - name: PORT
              value: "50054"
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: ClusterIP
  ports:
    - name: chat-service-port
      port: 50054
      targetPort: 50054
  selector:
    app: chat-service
