apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameprovider-service
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameprovider-service
  template:
    metadata:
      labels:
        app: gameprovider-service
    spec:
      containers:
        - name: gameprovider-service
          image: maplefighters/gameprovider-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
          env:
            - name: IP_ADDRESS
              value: 0.0.0.0:50052
            - name: RUST_BACKTRACE
              value: full
            - name: RUST_LOG
              value: info
            - name: CONFIG_SOURCE
              value: v1.0
            - name: CONFIG_ENVIRONMENT
              value: Production
          resources:
            requests:
              cpu: 100m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gameprovider-service
  namespace: maple-fighters
spec:
  type: ClusterIP
  ports:
    - name: gameprovider-service-port
      port: 50052
      targetPort: 50052
  selector:
    app: gameprovider-service
