apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameprovider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameprovider-service
  template:
    metadata:
      labels:
        app: gameprovider-service
    spec:
      containers:
        - env:
            - name: GAME_SERVICES
              value: '[{"name":"Local Game","protocol":"ws","url":"localhost/game/"}]'
            - name: IP_ADDRESS
              value: 0.0.0.0:50052
            - name: RUST_BACKTRACE
              value: full
            - name: RUST_LOG
              value: info
          image: maplefighters/gameprovider-service:latest
          name: gameprovider-service
          ports:
            - containerPort: 50052
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gameprovider-service
spec:
  type: ClusterIP
  ports:
    - name: gameprovider-service-port
      port: 50052
      targetPort: 50052
  selector:
    app: gameprovider-service
