apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-auth
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-auth
  template:
    metadata:
      labels:
        app: mongo-auth
    spec:
      containers:
        - name: mongo-auth
          image: mongo:5.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      restartPolicy: Always
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-storage
  namespace: maple-fighters
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-auth
  namespace: maple-fighters
spec:
  type: ClusterIP
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-auth
