apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-auth
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-auth
  template:
    metadata:
      labels:
        app: mongo-auth
    spec:
      containers:
        - name: mongo-auth
          image: mongo:5.0.2
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-auth
  namespace: maple-fighters
spec:
  type: ClusterIP
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-auth
