apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-character
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-character
  template:
    metadata:
      labels:
        app: postgres-character
    spec:
      containers:
        - name: postgres-character
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-character
spec:
  type: ClusterIP
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-character
