apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: maple-fighters
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DATABASE_URL: postgres://postgres:postgres@postgres-character:5432/postgres
