name: Chat Service Build

on:
  push:
    branches: [develop]
    paths:
      - src/chat-service/src/**
  workflow_dispatch: # A way to trigger a workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: src/chat-service/package-lock.json
      - name: Chat App Install
        run: npm ci --prefix src/chat-service
      - name: Chat App Build
        run: npm run build --prefix src/chat-service
