name: DigitalOcean Deploy

on:
  workflow_dispatch:
    inputs:
      userName:
        description: 'User'
        required: true
        default: 'codingben'
        type: choice
        options:
        - codingben
      repoName:
        description: 'Repository'
        required: true
        default: 'maple-fighters'
        type: choice
        options:
        - maple-fighters
      branchName:
        description: 'Branch'
        required: true
        default: 'develop'
        type: choice
        options:
        - develop
      dockerComposeFile:
        description: 'Docker Compose File'
        required: true
        default: 'docker-compose.prod.yml'
        type: choice
        options:
        - docker-compose.prod.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            HOST=https://raw.githubusercontent.com
            USER=${{ inputs.userName }}
            REPO=${{ inputs.repoName }}
            BRANCH=${{ inputs.branchName }}
            FILE=${{ inputs.dockerComposeFile }}

            rm ${FILE}
            curl -s ${HOST}/${USER}/${REPO}/${BRANCH}/${FILE} -o ${FILE}

            export AUTH_DB_USER=${{ secrets.AUTH_DB_USER }}
            export AUTH_DB_PASSWORD=${{ secrets.AUTH_DB_PASSWORD }}
            export AUTH_DB_NAME=${{ secrets.AUTH_DB_NAME }}

            export CHARACTER_DB_USER=${{ secrets.CHARACTER_DB_USER }}
            export CHARACTER_DB_PASSWORD=${{ secrets.CHARACTER_DB_PASSWORD }}
            export CHARACTER_DB_NAME=${{ secrets.CHARACTER_DB_NAME }}
            
            docker-compose -f ${FILE} pull
            docker-compose -f ${FILE} up -d
            docker system prune -af
