name: DigitalOcean Deploy

on:
  workflow_dispatch:

env:
  DOCKER_COMPOSE_FILE: docker-compose.prod.yml
  DOCKER_COMPOSE_URL: https://raw.githubusercontent.com/benukhanov/maple-fighters/develop/docker-compose.prod.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            rm ${{ env.DOCKER_COMPOSE_FILE }}
            curl -s ${{ env.DOCKER_COMPOSE_URL }} -o ${{ env.DOCKER_COMPOSE_FILE }}
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d
            docker system prune -af
