name: Frontend Build

on:
  push:
    branches: [develop]
    paths:
      - src/frontend/src/**
  workflow_dispatch: # A way to trigger a workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json
      - name: Frontend App Install
        run: npm ci
      - name: Frontend App Build
        run: npm run build
