name: Frontend Build

on:
  push:
    branches: [main]
    paths:
      - src/frontend/**
  pull_request:
    branches: [main]
    paths:
      - src/frontend/**
  workflow_run:
    workflows: [Unity Build Updater]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch
        run: |
          if [[ "${{ github.ref }}" != 'refs/heads/main' ]]; then 
            echo "This is not main branch. Exiting..."
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json
      - name: Frontend App Install
        run: npm ci --prefix src/frontend
      - name: Frontend App Build
        run: npm run build --prefix src/frontend
