name: Frontend Docker Build And Push

on:
  workflow_dispatch:
    # Left blank intentionally

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build And Push
        uses: docker/build-push-action@v4
        with:
          context: ./src/frontend
          build-args: |
            "ENVIRONMENT=Production"
          file: ./src/frontend/Dockerfile
          push: true
          tags: maplefighters/frontend:2.0.0
          platforms: linux/amd64,linux/arm64/v8
      - name: Build And Push (Develop)
        uses: docker/build-push-action@v4
        with:
          context: ./src/frontend
          build-args: |
            "ENVIRONMENT=Development"
          file: ./src/frontend/Dockerfile
          push: true
          tags: maplefighters/frontend:develop
          platforms: linux/amd64,linux/arm64/v8
