name: GameProvider Docker Build And Push

on:
  workflow_run:
    workflows: [GameProvider Service Build]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build And Push
        uses: docker/build-push-action@v2
        with:
          context: ./src/gameprovider-service
          file: ./src/gameprovider-service/Dockerfile
          push: true
          tags: maplefighters/gameprovider-service:latest
