name: Game Service Build

on:
  push:
    branches: [develop]
    paths:
      - src/game-service/Game.Application/**
      - src/game-service/Game.PhysicsTests/**
  workflow_dispatch: # A way to trigger a workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Game Application Build
        run: dotnet build src/game-service/Game.Application -c Release
      - name: Game Physics Tests Build
        run: dotnet build src/game-service/Game.PhysicsTests -c Release
