name: Unity Build Updater

on:
  workflow_run:
    workflows: [Unity Build]
    types: [completed]

env:
  TOKEN: ${{ secrets.ARTIFACTS_TOKEN }}

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Game Data
        run: |
          # Set Variables
          USER=codingben
          REPO=maple-fighters
          WORKFLOW_FILE=unity-build.yml
          ARTIFACT_NAME=Build.zip
          PLATFORM=WebGL
          BUILD_DIR=${PLATFORM}/${PLATFORM}/Build/*
          FILES_DIR=src/frontend/public/files
          # Download Game Files
          WORKFLOW_URL=https://api.github.com/repos/${USER}/${REPO}/actions/workflows/${WORKFLOW_FILE}/runs?per_page=1
          ARTIFACTS_URL=$(curl -s ${WORKFLOW_URL} | jq -r '.workflow_runs[].artifacts_url')
          ZIP_URL=$(curl -s ${ARTIFACTS_URL} | jq -r '.artifacts[].archive_download_url')
          curl -s -L -H "Authorization: token ${{ env.TOKEN }}" ${ZIP_URL} -o ${ARTIFACT_NAME}
          # Update Game Files
          unzip ${ARTIFACT_NAME}
          mv ${BUILD_DIR} ${FILES_DIR}
          rm ${ARTIFACT_NAME}
          rm -r ${PLATFORM}
      - uses: EndBug/add-and-commit@v8
        with:
          message: "build(frontend): update game files"
          default_author: github_actions
