name: Update Game Data

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.ARTIFACTS_TOKEN }}
  ARTIFACT_NAME: Build.zip

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Zip URL
        run: |
          WORKFLOW_URL=https://api.github.com/repos/benukhanov/maple-fighters/actions/workflows/unity-build.yml/runs\?per_page\=1
          ARTIFACTS_URL=$(curl -s ${WORKFLOW_URL} | jq -r '.workflow_runs[].artifacts_url')
          ZIP_URL=$(curl -s ${ARTIFACTS_URL} | jq -r '.artifacts[].archive_download_url')
          curl -L -H "Authorization: token ${{ env.TOKEN }}" ${ZIP_URL} -o ${{ env.ARTIFACT_NAME }}
          unzip ${{ env.ARTIFACT_NAME }}
          mv WebGL/WebGL/Build/* src/frontend/public/files
          rm ${{ env.ARTIFACT_NAME }}
          rm -r WebGL
